users:
  - user:
      username: ''
      #password 激活后的密码
      password: ''
      #address 地址，显示在提交按钮上方的定位区域
      address: 江苏省徐州市铜山区行健西路
      
cpdaily:
  defaults:
    - default:
        title: 你的学生类别
        type: 2
        value: 本科生
    - default:
        title: 你的生源地
        type: 2
        value: 内地
    - default:
        title: 你今天晨检体温是多少
        type: 2
        value: 36~37.2℃（正常体温）
    - default:
        title: 你今天午检体温是多少
        type: 2
        value: 36~37.2℃（正常体温）
    - default:
        title: 你今天是为疑似/确诊新冠肺炎患者？
        type: 2
        value: 否
    - default:
        title: 你今天是否与疑似/确诊新冠肺炎患者有密切接触？
        type: 2
        value: 否
    - default:
        title: 你今天是否有咳嗽、乏力等症状
        type: 2
        value: 否
    - default:
        title: 你今天是否就诊或住院
        type: 2
        value: 否
    - default:
        title: 你是否被隔离，如果被隔离，请选择你的隔离方式
        type: 2
        value: 否
    - default:
        title: 目前是否在学校
        type: 2
        value: 是
    - default:
        title: 目前你所在城市
        type: 1
        value: 江苏省/徐州市/铜山区
    - default:
        title: 今天是否有跨区域行程异动（注：指跨县及以上行政区域，徐州市内各区之间的交通活动不用填报）
        type: 2
        value: 否
    - default:
        title: 本人是否承诺以上所填报的全部内容属实、准确，不存在任何隐瞒、不实和遗漏之处
        type: 2
        value: 是